name: Publish Python Package to PyPI on Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: pipx install poetry
    
    - name: Configure Poetry
      run: poetry config virtualenvs.create false
    
    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi
    
    - name: Build package
      run: poetry build
    
    - name: Publish to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
